export const data = [
  {
    title: 'Keto Big Mac Bowl',
    author: 'Joe Bloggs',
    description: '1. ',
    time: '21-30 mins',
    cost: '£5-15',
    nutrition: 'Keto',
    ingredients:
      'Ground beef 500g, Worcestershire sauce 1 tablespoon, Garlic powder 1 teaspoon, Salt 1 teaspoon, Pepper ½ teaspoon, Diced onions 50g, Shredded cheddar cheese 200g, Cabbage thinly shredded 400g, Dill Pickle slices 16',
    image: 'TEXT',
    serves: '4',
    rating: 5,
    rating_entries: 23,
    cloudinary_id: 'none',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660138836/Keto-Big-Mac-Bowl_IG-6-660x660_upxoh9.webp',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'John Doe',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050221/sandie-clarke-DRs0juEZtsc-unsplash_gy32ui.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050213/thomas-tucker-MNtag_eXMKw-unsplash_f9bdsg.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050205/alena-ganzhela-MONzTP2XxUE-unsplash_mh1epp.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050188/scott-eckersley-R-7_ErUOLxw-unsplash_v2gawj.jpg',
  },
];