export const data = [
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050237/louis-hansel-1xqld2N7YAw-unsplash_wmh6up.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050221/sandie-clarke-DRs0juEZtsc-unsplash_gy32ui.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050213/thomas-tucker-MNtag_eXMKw-unsplash_f9bdsg.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050205/alena-ganzhela-MONzTP2XxUE-unsplash_mh1epp.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050188/scott-eckersley-R-7_ErUOLxw-unsplash_v2gawj.jpg',
  },
];